### PR TITLE
Committing Test2 to BranchX

### PR DESCRIPTION
**Pull request by saga125**
Hi,

I have committed Test2. Please review and approve.

Regards,
Saga

### CODE REVIEW

**Comment by Sagarika12ry** [comment]
Hi Saga,

Your code looks good. Please add one more check.

Regards,
P

**Comment by saga125** [comment]
Hi P,

I have added additional checks. Please approve.

Regards,
Saga

**Comment by Sagarika12ry** [comment]
Hi Saga,

Your code looks good. Give another if condition.

Regards,
P

**Comment by saga125** [comment]
Hi P,

I have added another  'if' condition. Please approve.

Regards,
Saga

**Comment by Sagarika12ry** [comment]
Hi Saga,

Your code looks good. Please go ahead with merge to master branch.

Regards,
P

**Pull request merged**
